spring:
  application.name: spring-ai-rag-demo
  datasource:
    url: jdbc:postgresql://localhost:5433/rag_demo
    username: postgres
    password: postgres
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:ADD_YOUR_OPENAI_API_KEY_HERE}
      chat.options.model: gpt-4o-mini
      chat.options.temperature: 0
      embedding.options.model: text-embedding-3-small
    vectorstore.pgvector:
      initialize-schema: true
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 1536
server.port: 8080
